[package]

name = "utils"
version = "0.0.1"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]

[dependencies]
rand = "0.1.2"
rustc-serialize = "0.2.12"

[dependencies.time]
git = "https://github.com/rust-lang/time"
