[package]

name = "utils"
version = "0.0.1"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]

[dependencies]
rustc-serialize = "0.2.10"

[dependencies.time]
git = "https://github.com/rust-lang/time"
